apiVersion: v1
kind: ReplicationController
metadata:
    labels: 
        app: nginx
    name: nginx
spec:
    replicas: 2
    selector:
        app: nginx
    template:
        metadata:
            labels:
                app: nginx
            name: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
                  - containerPort: 80
              